# Generated by Django 3.2.20 on 2023-08-07 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StaffInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('age', models.IntegerField(verbose_name='age')),
                ('create_time', models.DateField(verbose_name='Hire Date')),
                ('depart', models.CharField(max_length=64, verbose_name='Department')),
                ('mobile_number', models.CharField(blank=True, max_length=32, null=True)),
                ('street_address1', models.CharField(blank=True, max_length=80, null=True)),
                ('address2', models.CharField(blank=True, max_length=80, null=True)),
                ('city', models.CharField(blank=True, max_length=40, null=True)),
                ('county', models.CharField(blank=True, max_length=80, null=True)),
                ('gender', models.SmallIntegerField(choices=[(1, 'Male'), (2, 'Female')])),
            ],
        ),
    ]
